
POST http://localhost:3000/albums/list

###
GET http://localhost:3000/albums/1


###
POST http://localhost:3000/albums
Content-Type: application/json

{
    "title": "Summer Memories",
    "user": {
      "id": 3,
      "name": "Clementine Bauch",
      "username": "Samantha",
      "email": "Nathan@yesenia.net"
    }
  }

###

PATCH http://localhost:3000/albums/1
Content-Type: application/json

{
    "id": 1,
    "title": "Summer Memories2",
    "user": {
        "id": 2
    }
}

###
DELETE http://localhost:3000/albums/11
