
GET http://localhost:3000/posts/1/comments

###
GET http://localhost:3000/posts/1/comments/1


###
POST http://localhost:3000/posts/28/comments
Content-Type: application/json

{
    "name": "Bharat Patel",
    "email": "bharat@email.com",
    "body": "Great post! I completely agree with your thoughts on exploring nature. There's something truly magical about it."
}

###

PATCH http://localhost:3000/posts/28/comments/96
Content-Type: application/json

{
  "body": "Great post! I completely agree."
}

###
DELETE http://localhost:3000/posts/1/comments/96
